name: Deploy multi-containers
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - run: docker build -t annabelleew/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true annabelleew/react-test npm test

      - name: Build production client
        run: docker build -t annabelleew/multi-client ./client

      - name: Build production nginx
        run: docker build -t annabelleew/multi-nginx ./nginx

      - name: Build production server
        run: docker build -t annabelleew/multi-server ./server

      - name: Build production worker
        run: docker build -t annabelleew/multi-worker ./worker

      - name: Push multi-client to Docker Hub
        run: docker push annabelleew/multi-client

      - name: Push multi-nginx to Docker Hub
        run: docker push annabelleew/multi-nginx

      - name: Push multi-server to Docker Hub
        run: docker push annabelleew/multi-server

      - name: Push multi-worker to Docker Hub
        run: docker push annabelleew/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: TBD
          environment_name: TBD
          existing_bucket_name: TBD
          region: TBD
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
